### ISSUE TITLE
readFile() returns encoded string

### ISSUE THREAD

**Issue by egor-teapot** [sourcetoad/react-native-fs2#22]
ts
```
export const STORAGE:string = String(RNFS.ExternalDirectoryPath + "/")

...
RNFS.writeFile(await STORAGE+"some.txt", "some text", "utf8")
console.log(await RNFS.readFile(STORAGE+"some.txt", "utf8")) // returns YzI5dFpTQjBaWGgw
```

packages:
- react-native-fs2: 3.0.2
- react-native: 0.71.3
- react: 18.2.0

So, i tried out few decoders and this is what i found.

function returns
```
YzI5dFpTQjBaWGgw 
```

i decoded it from base64 to utf8
```
c29tZSB0ZXh0
```

and when i decode it from base64 to utf8 and i got
```
some text
```

Please can you fix this problem? I use this package for my qualifying work in college. Pretty please?

i builded app only for android huawei nova 10 SE EMUI 12.0.1

**Comment by iBotPeaches** [comment]
@egor-teapot - Just double checking.

 * You write a file to OS in `utf8`
 * You read that file via `readFile` with `utf8` encoding and expect the plaintext value, but were given the base64 representation of the value.
 
 Was this on Android or iOS or both?

**Comment by egor-teapot** [comment]
> 

1. Yes
2. Yes
3. i builded app only for android. huawei nova 10 SE EMUI 12.0.1

**Comment by egor-teapot** [comment]
> ts
> 
> ```
> export const STORAGE:string = String(RNFS.ExternalDirectoryPath + "/")
> 
> ...
> RNFS.writeFile(await STORAGE+"some.txt", "some text", "utf8")
> console.log(await RNFS.readFile(STORAGE+"some.txt", "utf8")) // returns YzI5dFpTQjBaWGgw
> ```
> 
> packages:
> 
>     * react-native-fs2: 3.0.2
> 
>     * react-native: 0.71.3
> 
>     * react: 18.2.0
> 
> 
> So, i tried out few decoders and this is what i found.
> 
> function returns
> 
> ```
> YzI5dFpTQjBaWGgw 
> ```
> 
> i decoded it from base64 to utf8
> 
> ```
> c29tZSB0ZXh0
> ```
> 
> and when i decode it from base64 to utf8 and i got
> 
> ```
> some text
> ```
> 
> Please can you fix this problem? I use this package for my qualifying work in college. Pretty please?
> 
> i builded app only for android huawei nova 10 SE EMUI 12.0.1


android/build.gradle
```
buildscript {
    ext {
        buildToolsVersion = "33.0.0"
        minSdkVersion = 21
        compileSdkVersion = 33
        targetSdkVersion = 33

        // We use NDK 23 which has both M1 support and is the side-by-side NDK version from AGP.
        ndkVersion = "23.1.7779620"
    }
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath("com.android.tools.build:gradle:7.3.1")
        classpath("com.facebook.react:react-native-gradle-plugin")
    }
}
```

**Comment by iBotPeaches** [comment]
@egor-teapot - Thanks for the find. We will have a 3.0.3 out today to resolve this.
