### ISSUE TITLE
downloadFile 并不是一个Promise对象 await无效

### ISSUE THREAD

**Issue by 16638964387** [sourcetoad/react-native-fs2#39]
RNFS.downloadFile({
            fromUrl: version.url as unknown as string,
            toFile: destinationPath,
          });

**Comment by iBotPeaches** [comment]
Do you have a stacktrace or RN version that led you to this? 

I can tell reading the docs that we have a mixup between the code comment and parameters, which may what you are running into.

> https://github.com/sourcetoad/react-native-fs2#downloadfile

It looks to be an object with jobId and promise, but the docs have it differently.
